### ISSUE TITLE
View for Map generation

### ISSUE THREAD

**Issue by Baret** [Baret/pltcmd#37]
**Basic idea/big picture**
While the game generates the map it would be interesting to see how it forms and evolves. The process takes some seconds so it might be possible to "spectate" it.

**Details**
Currently the game starts in the `GameView` which is only visible after map generation has finished. There could be a view displaying an abstract version of the `MutableWorld` while it is being generated, so you have some kind of loading screen. I imagine it being full window size, maybe with a border titled "generating world...". It juts has a `GameAreaComponent` which maps chunks of the `MutableWorld` to displayed tiles, which means when the window is 100 tiles wide and the world being generated has 1000 tiles in width, it would display the average type and height (or empty) of 10 tiles at each position.

**Technical background**
The new view would need to observe the `MutableWorld` and map generation would need to run asynchonously. So far I have 2 ideas of how this could be implemented, but better ones might exist ;)
- The view gets the `MutableWorld` as some kind of [observable property](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.properties/-delegates/observable.html) (though the native kotlin way might not be useful here). Maybe it would already be enough to let `MutableWorld` extend `BaseGameArea` and let Zircon do the rest.
- Every `IntermediateGenerator` sends an Event (i.e. over the Cobalt `EventBus`) after a step that might justify a redraw of the map. But this approach would need every future `IntermediateGenerator` to respect that kind of contract, which is not nice as it might be forgotten.

**Related issues/Prerequisites**
As we just finished #13 this might be started any time.

**Comment by Loomie** [comment]
To see anything I first build a title screen with a fixed text.

**Comment by Loomie** [comment]
Concept

UI:
A `GameWorld` displays the whole map. It is based on a `WorldMap` which requires at least one sector. Because only a single sector is visible at a time the full map will be scaled down to a single `Sector`.
The `MapBlock` needs to display nothing. It will use a question mark character with transparent background and default foreground color.

Communication and data:
The `MutableWorld` must fire an event whenever a Terrain changes. The model data must be translated to the UI. That is the coordinate must be scaled down and merged into a preview model first. Then the `GameWorld` must update the presentation of that tile. The logical world does not need to be changed and can stay immutable as the GameWorld currently does not use the WorldMap after creating its UI.

**Comment by Loomie** [comment]
Now there is a title screen with a fixed delay (1.5 s). During the map generation a map is shown almost fullscreen together with a progress bar and the percentage. After the generation a button is shown which must be clicked to continue.
